from scons_go_support import *
import os

# Build programs
# Modify this to suit your program
main_package = go_env.Go(target='echo.out', source='echo.go')
program = go_env.GoProgram(target='echo', source=[main_package])
