all: bill_of_materials

bill_of_materials: bill_of_materials.cpp part.cpp
	g++ -o bill_of_materials bill_of_materials.cpp part.cpp\
		-std=gnu++0x -lboost_date_time -lboost_filesystem -lboost_regex -g -Wall
