env = Environment(
    LIBPREFIX = "",
)

# Grab all the pkg-config stuff.
env.ParseConfig('pkg-config --cflags --libs gtk+-2.0')

conf = Configure(env)
if not conf.CheckLib("cairo"):
  print 'Could not find cairo library.'
  Exit(1)
conf.Finish()

env.SharedLibrary('example.c')
