all: heaps prim htable2 itoa fun_with_strings bintree

bintree: bintree.c
	gcc -Wall -o $@ $<

heaps: heaps.c
	gcc -Wall -o $@ $<

fun_with_strings: fun_with_strings.c
	gcc -Wall -g -o $@ $<

itoa: itoa.c
	gcc -Wall -o $@ $<

htable2: htable2.cpp
	g++ -g -Wall -o $@ $<

prim: prim.c
	gcc -Wall -o $@ $<
